name: 'irony_baseline'
checkpoint_interval: 0
log_interval: 5
batch_size: 32
epochs: 1000
weight_decay: 0.0
patience: 10
class_weights: False
data:
  dataset: irony
  features: [LIWC, afinn, semeval15, emolex, bing_liu, mpqa]
  embeddings: word2vec_300_6_20_neg.txt
  embeddings_dim: 300
  seq_len: 0
model:
  embed_finetune: False
  emb_size: 300
  embed_noise: 0.1
  embed_dropout: 0.2
  rnn_size: 500
  rnn_layers: 1
  rnn_dropout: 0.3
  pack: True
  clip: 5
  conc_emb: False
  conc_rnn: True

