name: "irony_concat"
checkpoint_interval: 0
log_interval: 5
batch_size: 64
epochs: 1000
weight_decay: 0.0
patience: 6
class_weights: True
data:
  dataset: irony
  features: LIWC
  features_dim: 73
  embeddings: word2vec_300_6_20_neg.txt
  embeddings_dim: 300
  seq_len: 0
model:
  embed_finetune: False
  emb_size: 300
  embed_noise: 0.1
  embed_dropout: 0.2
  rnn_size: 300
  rnn_layers: 1
  rnn_dropout: 0.3
  attention_type: concat
  pack: True
  clip: 5
